on: 
  [push]   


jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_KEY}}
