on: 
  push:
    branches: 
      - master 


jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Pull changes
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          sudo systemctl stop portfolio
          cd portfolio
          git pull
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_KEY}}
    - name: build react
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd portfolio
          yarn build
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_KEY}}
    - name: restart backend
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          sudo systemctl start portfolio
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_KEY}}
